### ISSUE TITLE
Difficult to follow wording

### ISSUE THREAD

**Issue by SixFiveSoftware** [editorscut/ec014dataflow#1]
<img width="1040" alt="Screenshot 2024-01-28 at 8 39 19 PM" src="https://github.com/editorscut/ec014dataflow/assets/2272819/3faf5ce7-0053-4212-90c4-b484e3175a62">

In the first paragraph here, it's difficult to follow the sentence starting "In the end".

**Comment by dimsumthinking** [comment]
Thank you - I fixed this when you raised it and forgot to close this issue. Thank you again, Daniel
