### ISSUE TITLE
App crashes on the  Simulator if ConcurrencyDebug is activated in Scheme.

### ISSUE THREAD

**Issue by HSV0815** [editorscut/ec014dataflow#2]
Versions: 

Xcode: 
Version 15.2 (15C500b)

Simulator: 
Version 15.2 (1019)
SimulatorKit 937
CoreSimulator 947.7

iPhone 15 Pro (17.2)

Book: 
The Mystery of the Mutating Mannequin - DataFlowBeta2.pdf

Source code:
ec014dataflow-main/Chapter04/07/RoadTripCD/ 
Commit: [a296da6](https://github.com/editorscut/ec014dataflow/commit/a296da69ebcc3e28587e0d81837d6842dd985cc4)

Description: 
The app runs without errors as long as ConcurrencyDebug is not activated but crashes otherwise when you press “+” to add another journey on the simulator.
As you probably know or already guessing the culprit is at the line 11 in the file Journey+CoreDataClass.swift. Changing the code from newBackgroundContext() to viewContext corrects the error.

Thank you very much for the books - please keep up the good work.

Screenshots:

<img width="1376" alt="Screenshot 2024-02-20 at 01 31 29" src="https://github.com/editorscut/ec014dataflow/assets/14965183/611ec4aa-b49d-4a91-b543-abbc81c05bf7">

<img width="932" alt="Screenshot 2024-02-20 at 01 29 37" src="https://github.com/editorscut/ec014dataflow/assets/14965183/9e7ffbc4-30a8-40e6-a020-5ce908afabdf">

<img width="932" alt="Screenshot 2024-02-20 at 01 28 46" src="https://github.com/editorscut/ec014dataflow/assets/14965183/8673ac7b-6086-4e6c-a87c-cc1e2335e4c5">

**Comment by dimsumthinking** [comment]
Thank you - You are, of course, correct. I apologize and have fixed this.

Thank you again for taking the time to submit this, the update is already in the code download and will be in the next release of the book later this week.

Best, Daniel
